# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b9be6c9442af9a6bcc553cb081a2dcbd66f2e1d6a7b9a8d6d4718eb4f6660e98d19670bae5ff39d24fd1d6b243b937e90e7f6982e59d1a22a33c62eb83dacf1

test:
  secret_key_base: 7782f648e15375c6d53e60c3819de3614e3ccaebb8b4393771561b6d28c522b63201b9cb330dbe3d4869fab1d7c1fd5cb4ada0f09e3dc37aef7cf33f743f271e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
