# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de8399bb9af8d22cde2da9430b6d77bc458c90b65de4ce8985a08dc7059176b3abd03cf7f532fe91795a4237629c10cc9941657b1485fe111ff7b3c3b5f16d1b

test:
  secret_key_base: 6eb2a7e8d837a09887ff71e202afdde51532df9b2a3fe563b5bcde1ae39144529bf9573cfbb60bb598f15823226c54f585bdbdb09685d9ae11ed90776315d517

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
